(function(g){var window=this;'use strict';var aob=function(a){g.X.call(this,{I:"div",T:"ytp-inline-preview-ui"});this.xg=!1;this.player=a;this.V(a,"onStateChange",this.sR);this.V(a,"videodatachange",this.vx);this.V(a,"onInlinePreviewModeChange",this.H6);this.Cf=new g.dr(this.Jw,null,this);g.H(this,this.Cf)},J6=function(a){g.dT.call(this,a);
this.j=new aob(this.player);g.H(this,this.j);this.j.hide();g.cS(this.player,this.j.element,4);a.isInline()&&(this.load(),a=a.getRootNode(),g.or(a,["ytp-inline-preview-mode","ytp-no-contextmenu"]))};
g.x(aob,g.X);g.k=aob.prototype;
g.k.gO=function(){this.tooltip=new g.DV(this.player,this);g.H(this,this.tooltip);g.cS(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.fd=new g.JT(this.player);g.H(this,this.fd);this.yk=new g.X({I:"div",Na:["ytp-inline-preview-scrim"]});g.H(this,this.yk);this.yk.Ha(this.element);this.V(this.yk.element,"click",this.TI);this.Oj=new g.wV(this.player,this,300);g.H(this,this.Oj);this.Oj.Ha(this.yk.element);this.controls=new g.X({I:"div",T:"ytp-inline-preview-controls"});g.H(this,this.controls);
this.controls.Ha(this.element);var a=new g.OU(this.player,this,!1);g.H(this,a);a.Ha(this.controls.element);a=new g.uV(this.player,this);g.H(this,a);a.Ha(this.controls.element);this.Sc=new g.VU(this.player,this);g.H(this,this.Sc);g.cS(this.player,this.Sc.element,4);this.V(this.player,"appresize",this.Mb);this.V(this.player,"fullscreentoggled",this.Mb);this.Mb()};
g.k.show=function(){g.er(this.Cf);this.xg||(this.gO(),this.xg=!0);0!==this.player.getPlayerState()&&g.X.prototype.show.call(this);this.Sc.show();this.player.Ra("onInlinePreviewUiReady")};
g.k.hide=function(){this.Cf.stop();g.X.prototype.hide.call(this);this.player.isInline()||this.xg&&this.Sc.hide()};
g.k.ya=function(){g.X.prototype.ya.call(this)};
g.k.TI=function(a){a.target===this.yk.element&&this.player.Ra("onExpandInlinePreview",a)};
g.k.H6=function(){g.rr(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.cf=function(){this.Sc.Dc();this.Oj.Dc()};
g.k.Jw=function(){this.cf();g.er(this.Cf)};
g.k.Mb=function(){g.gV(this.Sc,0,this.player.sb().getPlayerSize().width,!1);g.WU(this.Sc)};
g.k.sR=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.vx=function(a,b){if(this.player.isInline()){g.rr(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.mL);var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.rr(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Fc=function(){return this.tooltip};
g.k.Lg=function(){return!1};
g.k.Mg=function(){return!1};
g.k.zm=function(){return!1};
g.k.PJ=function(){};
g.k.wq=function(){};
g.k.jz=function(){};
g.k.un=function(){return null};
g.k.oH=function(){return null};
g.k.vN=function(){return new g.ue(0,0)};
g.k.Qk=function(){return new g.wo(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Tw=function(a,b,c,d,e){var f=d=0,h=0,l=g.Ko(a);if(b){c=g.mr(b,"ytp-mute-button");var m=g.mr(b,"ytp-subtitles-button"),n=g.Io(b,this.element);b=g.Ko(b);d=n.y+40;if(m||c)h=n.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.sb().getPlayerSize().width;h=g.oe(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.Zp=function(){};
g.k.nm=function(){return!1};
g.k.pF=function(){};
g.k.aB=function(){};
g.k.Rr=function(){};
g.k.Qr=function(){};
g.k.Fy=function(){};
g.k.Zs=function(){};
g.k.YE=function(){};g.x(J6,g.dT);J6.prototype.yl=function(){return!1};
J6.prototype.load=function(){this.player.hideControls();this.j.show()};
J6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.cT("inline_preview",J6);})(_yt_player);
